//מערך אוביקטים כל אוביקט הוא מוצר שטיח
CarpetProducts = [
    {
        "name": "Abstract geometric vintage",
        "description": "The medieval mosaic-style rug comes with impressive ancient geometric shapes, beautiful color combinations and spectacular contrast between them. The great advantage of the rug is the ability to integrate in modern living rooms and vintage salons",
        "price": 200,
        "imagee": 'carp1n.jpg',
        "category": "Classic Carpet",
        "amount": 25,
        "entrytime": "11/1/2020",
        "manufacturer": "Machine work",
        "arrcapter": [{ "CountryManufacture": "Turkey" }, { "material":"polyester"}],
    },
    {
        "name": "Vintage Cotton Chanel Medallion",
        "description": "The rug in the polished antique style will fit the living room, bedroom. The jacquard rug made of 100% cotton has style, presence, change and luxury. The delicate and elegant rub that illustrates its vintage aspect and the impressive medallion.",
        "price": 300,
        "imagee": "carp2n.jpg",
        "category": "Classic Carpet",
        "amount": 12,
        "entrytime": "2/1/2020",
        "manufacturer": "Machine work",
        "arrcapter": [{"CountryManufacture": "India"},{"material": "cotton"}],
    },
    {
        "name": "Vintage medallion model Julia",
        "description": "Vintage rug, modern luxury medallion in black and white, Julia model. The rug has extensive florality and elegant contrasts between its colors that give it sharpness and luxury.",
        "price": 780,
        "imagee": "carp3n.jpg",
        "category": "Classic Carpet",
        "amount": 12,
        "entrytime": "3/6/2020",
        "manufacturer": "Machine work",
        "arrcapter": [{ "CountryManufacture": "Turkey" }, { "material": "Hitst" }],
    },
    {
        "name": "Vintage purple medallion model Florence",
        "description": "The elegant and special rug will fit well in the living room, bedroom and office. The rug has an impressive medallion and charming archaic elements. It is strong, stable on the ground, practical and easy to clean.",
        "price": 800,
        "imagee": "carp4n.jpg",
        "category": "Classic Carpet",
        "amount": 9,
        "entrytime": "8/1/2021",
        "manufacturer": "Machine work",
        "arrcapter": [{ "CountryManufacture": "Turkey" }, { "material": "Hitst"}],
    },
    {
        "name": "Classic floral red Pompeii",
        "description": "Luxury floral classic rug in red, beige, green and blue. Manufactured by machine. He will put in a lot of style. In addition, it is versatile, strong, durable, stable on the ground, practical and easy to clean.",
        "price": 350,
        "imagee": "carp5n.jpg",
        "category": "Classic Carpet",
        "amount": 23,
        "entrytime": "3/12/2020",
        "manufacturer": "Machine work",
        "arrcapter": [{ "CountryManufacture": "Belgium" }, { "material":"Hitst"}],
    },
    {
        "name": "Shaggy modern thick splendid pompoms",
        "description": "The country-style rug will suit the living room, bedroom or room. The carpet is very thick which indicates its high quality. It is very dense, practical and easy to clean. Can be washed by hand in lukewarm water.",
        "price": 500,
        "imagee": "carp6n.jpg",
        "category": "Turkish shaggy carpet",
        "amount": 24,
        "entrytime": "23/10/2019",
        "manufacturer": "Machine work",
        "arrcapter": [{ "CountryManufacture": "Turkey" }, { "material": "Hitst" }],
    },
    {
        "name": "Shaggy Geometric Charlotte",
        "description": "Modern cotton shaggy rug. The luxury rug is suitable for the living room, bedroom, children's room. The rug is made of 100% cotton, with geometric shapes. The rug is versatile, durable, strong, dense, thick, and easy to clean.",
        "price": 350,
        "imagee": "carp7n.jpg",
        "category": "Turkish shaggy carpet",
        "amount": 14,
        "entrytime": "12/7/2020",
        "manufacturer": "Machine work",
        "arrcapter": [{ "CountryManufacture": "India" }, { "material": "cotton" }],
    },
    {
        "name": "Moroccan barbarian Troy",
        "description": "It is made from 100% pure New Zealand wool. The rustic rug will suit the living room, bedroom, play area. That is, it will suit all design styles. In addition it is strong, thick, very pleasant to the touch, practical.",
        "price": 460,
        "imagee": "carp8n.jpg",
        "category": "Turkish shaggy carpet",
        "amount": 27,
        "entrytime": "29/5/2019",
        "manufacturer": "Oriane",
        "arrcapter": [{ "CountryManufacture": "India" }, { "material": "New Zealand wool" }],
    },
    {
        "name": "Shaggy Blue Rainbow model",
        "description": "A luxurious modern light blue blue shaggy rug, model Rainbow for the living room, bedroom. The country style rug together with the amazing mix between its colors will add a lot of style to the space it is in. It is durable, thick, practical and easy to clean.",
        "price": 540,
        "imagee": "carp9n.jpg",
        "category": "Turkish shaggy carpet",
        "amount": 8,
        "entrytime": "17/2/2018",
        "manufacturer": "Machine work",
        "arrcapter": [{ "CountryManufacture": "Turkey" }, { "material": "Hitst" }],
    },
    {
        "name": "Shaggy Colorado Cream Abstract",
        "description": "The country-style rug will suit the living room, children's room, hallway and office. Very thick, extremely dense and pleasant to the touch. In addition, the carpet is strong, durable, stable on the ground, practical and easy to clean.",
        "price": 480,
        "imagee": "carp10n.jpg",
        "category": "Turkish shaggy carpet",
        "amount": 11,
        "entrytime": "26/4/2019",
        "manufacturer": "Machine work",
        "arrcapter": [{ "CountryManufacture": "Turkey" }, { "material": "Hitst" }],
    },



]


carpetPurchases = [];
customers = [];